DATASET:
  TRAIN_IMAGES: "./datasets/merged/train/images"
  TRAIN_MASKS: "./datasets/merged/train/labels"
  VAL_IMAGES: "./datasets/merged/val_clinic/images"
  VAL_MASKS: "./datasets/merged/val_clinic/labels"

SAM:
  CHECKPOINT: "./sam/checkpoints/sam_vit_b_01ec64.pth"
  CHECKPOINT_TYPE: "vit_b" # vit_b, vit_l, vit_h
  FINETUNE:
    IMAGE_ENCODER: False
    PROMPT_ENCODER: False
    MASK_DECODER: True

TRAIN:
  BATCH_SIZE: 1
  EPOCHS: 1
  LEARNING_RATE: 0.0001
  IMAGE_SIZE: 1024
