DATASET:
  TRAIN_IMAGES: "./datasets/Merged_newest/train/images"
  TRAIN_MASKS: "./datasets/Merged_newest/train/labels"
  VAL_IMAGES: "./datasets/Merged_newest/val/images"
  VAL_MASKS: "./datasets/Merged_newest/val/labels"

SAM:
  CHECKPOINT: "./sam/checkpoints/sam_vit_b_01ec64.pth"
  CHECKPOINT_TYPE: "vit_b" # [vit_b, vit_l, vit_h] Adjust checkpoint path above
  ORIG: True
  FINETUNE:
    IMAGE_ENCODER:
      ENABLED: False
      LEARNING_RATE: 0.0
      WEIGHT_DECAY: 0.0
    PROMPT_ENCODER:
      ENABLED: False
    MASK_DECODER:
      ENABLED: True
      LEARNING_RATE: 0.00001
      WEIGHT_DECAY: 0.001

TRAIN:
  BATCH_SIZE: 8
  EPOCHS: 100
  IMAGE_SIZE: 1024
  DUMMY_STEP: 32 # Grid step for dummy SAM prompt
  NUM_WORKERS: 4 # 0 - Multiprocessing not enabled; [1-10] Number of dataloader workers
