DATASET:
  TRAIN_IMAGES: "./datasets/Kvasir-SEG_splitted/train/images"
  TRAIN_MASKS: "./datasets/Kvasir-SEG_splitted/train/labels"
  VAL_IMAGES: "./datasets/Kvasir-SEG_splitted/val_kvasir/images"
  VAL_MASKS: "./datasets/Kvasir-SEG_splitted/val_kvasir/labels"

SAM:
  CHECKPOINT: "./sam/checkpoints/sam_vit_b_01ec64.pth"
  CHECKPOINT_TYPE: "vit_b" # vit_b, vit_l, vit_h
  FINETUNE:
    IMAGE_ENCODER: False
    PROMPT_ENCODER: False
    MASK_DECODER: True

TRAIN:
  BATCH_SIZE: 8
  EPOCHS: 10
  LEARNING_RATE: 0.01
  IMAGE_SIZE: 256
  NUM_WORKERS: 0
