DATASET:
  TRAIN_IMAGES: "./datasets/Kvasir-SEG_splitted/train/images"
  TRAIN_MASKS: "./datasets/Kvasir-SEG_splitted/train/labels"
  VAL_IMAGES: "./datasets/Kvasir-SEG_splitted/val_kvasir/images"
  VAL_MASKS: "./datasets/Kvasir-SEG_splitted/val_kvasir/labels"

SAM:
  CHECKPOINT: "./sam/checkpoints/sam_vit_b_01ec64.pth"
  CHECKPOINT_TYPE: "vit_b" # [vit_b, vit_l, vit_h] Adjust checkpoint path above
  ORIG: True
  FINETUNE:
    IMAGE_ENCODER: True
    PROMPT_ENCODER: False
    MASK_DECODER: False

TRAIN:
  BATCH_SIZE: 1
  EPOCHS: 100
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.001
  IMAGE_SIZE: 1024
  NUM_WORKERS: 4 # 0 - Multiprocessing not enabled; [1-10] Number of dataloader workers
